title: Has Signal Been Hacked?
description: A site to debunk rumors about Signal being hacked. 
theme: jekyll-theme-slate
url: "https://securing-change.github.io/hassignalbeenhacked/"
markdown: CommonMark
commonmark:
  options: ["hardbreaks"]
hero_file: "hero-no.md"
favicon: "/assets/images/favicon_no.png"
plugins:
  - jekyll-last-modified-at